<Project> 

<Import Project="packages\Microsoft.Windows.WDK.x64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.x64.props" 
    Condition="Exists('packages\Microsoft.Windows.WDK.x64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.x64.props') and '$(Platform)' == 'x64'"/> 

<Import Project="packages\Microsoft.Windows.WDK.arm64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.arm64.props" 
    Condition="Exists('packages\Microsoft.Windows.WDK.arm64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.arm64.props') and '$(Platform)' == 'ARM64'"/>

<Import Project="packages\Microsoft.Windows.SDK.CPP.x64.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.x64.props" 
    Condition="Exists('packages\Microsoft.Windows.SDK.CPP.x64.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.x64.props') and '$(Platform)' == 'x64'"/> 
    
<Import Project="packages\Microsoft.Windows.SDK.CPP.arm64.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.arm64.props" 
    Condition="Exists('packages\Microsoft.Windows.SDK.CPP.arm64.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.arm64.props') and '$(Platform)' == 'ARM64'"/>

<Import Project="packages\Microsoft.Windows.SDK.CPP.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.props" 
    Condition="Exists('packages\Microsoft.Windows.SDK.CPP.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.props')"/> 

<PropertyGroup>
  <!-- EnableTestSign left at default (true): DriverSign signs dll + cat using WDKTestCert -->
  <SkipPackageVerification>true</SkipPackageVerification>
  <InfToolPath Condition="'$(InfToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x64\</InfToolPath>
  <Inf2CatToolPath Condition="'$(Inf2CatToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x86\</Inf2CatToolPath>
  <DrvCatToolPath Condition="'$(DrvCatToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x64\</DrvCatToolPath>
  <TraceWppToolPath Condition="'$(TraceWppToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x86\</TraceWppToolPath>
  <WmimofckToolPath Condition="'$(WmimofckToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x64\</WmimofckToolPath>
  <BinplaceToolPath Condition="'$(BinplaceToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x64\</BinplaceToolPath>
  <MessageCompileToolPath Condition="'$(MessageCompileToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x64\</MessageCompileToolPath>
  <CtrppToolPath Condition="'$(CtrppToolPath)' == '' and '$(WDKContentRoot)' != ''">$(WDKContentRoot)\bin\10.0.28000.0\x64\</CtrppToolPath>
</PropertyGroup>

</Project> 
